### ISSUE TITLE
[ERROR] - This service has been suspended.

### ISSUE THREAD

**Issue by guiireal** [Bes-js/herc.ai#16]
Hey guys, how's it going?

First of all, congrats on the project!

I noticed that the base API link: `https://hercai.onrender.com/v3/hercai` is returning:

"This service has been suspended."

Not sure if you had a chance to check it out today.

![image](https://github.com/user-attachments/assets/81fb640d-1dac-42da-9fc5-35c96ad4196e)

**Comment by Bes-js** [comment]
solved render problem, try again.

**Comment by guiireal** [comment]
Great!
