### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by maminiainalaic** [Bes-js/herc.ai#2]
Hello, can you help me for my commercial chatbot , just i wanna do some personalization on the params to the api. So i just know if i can have my own api server like yours on render? Pls

**Comment by maminiainalaic** [comment]
i wanna continue the conversation

**Comment by Bes-js** [comment]
You can use Hercai on your own API, but you cannot change its name or remove it. If it is detected, you will be blocked through the API.

**Comment by maminiainalaic** [comment]
> You can use Hercai on your own API, but you cannot change its name or remove it. If it is detected, you will be blocked through the API.

how about the following of the conversation
