### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by ezekiel747** [Bes-js/herc.ai#5]
I'm trying to run the simple example in the readme file.

```
/* Importing The Package */
const { Hercai } = require('hercai');

const herc = new Hercai();

/* Available Models */
/* "v2" , "beta" , "v3-beta" */
/* Default Model; "v2" */
herc.question({model:"v2",content:"hi, how are you?"}).then(response => {
console.log(response.reply);
/* The module will reply based on the message! */

});
```

I get Error: Request failed with status code 500
Are there temp issues? Does it usually work? Should i try later?

**Comment by Scraper001** [comment]
I have the same issue, is the code still working for you? or nah? please respond

**Comment by Scraper001** [comment]
Thanks MASTER!!!! you saved my upcoming thesis defense ;>
